/*SOSO Map API beta 1.0.120307.1 @Tencent Research*/
(function(t){function F(a,c){var f=a.get("map"),e=a.get("path"),g=document.createElement("div"),b=document.createElement("span");g.appendChild(b);b="width:14px;height:14px;cursor:pointer;background-image:url("+(a.get("editIconUrl_")||u.domain+"imgs/poly.png")+");vertical-align:top;margin-left:3px;";var d=document.createElement("img");d.style.cssText=b+"background-position:-50px 0;";d.src=u.domain+"imgs/transparent.gif";g.appendChild(d);d.title=r.PolyEditLabel.remove;var l=document.createElement("img");
l.style.cssText=b+"background-position:-36px 0;";l.src=u.domain+"imgs/transparent.gif";g.appendChild(l);j.addDomListener(l,"click",function(){a.set("map",null)});l.title=a.get("fillColor")?r.PolyEditLabel.destroyPolygon:r.PolyEditLabel.destroyPolyline;var k=new A({offset:new v(8,0),position:e[c],content:g,visible:false,style:{},map:f});j.addDomListener(d,"click",function(){var m=k.get("pathIndex_");a.get("path").splice(m,1);a.notify("path")});j.addListener(k,"mouseover",function(){k.setZIndex(1E4);
if(!a.get("hasLabel")){var m=a.get("labelListener_");if(m){clearTimeout(m);a.set("labelListener_",null)}}});j.addListener(k,"mouseout",function(){k.setZIndex(k.get("pathIndex_")+10);a.get("hasLabel")||a.toggleLabel(false)});return k}function B(a,c){var f=document.createElement("div");f.style.cssText="position:absolute;width:12px;height:12px;cursor:pointer;z-index:-10;";if(c!=-1)f.title=r.PolyEditLabel.drag;var e=null;j.addDomListener(f,"mousedown",function(b){j.stopEvent(b);if(c==-1)e=this._lineIndex});
var g=null;w.enableDrag(f,document.body.parentNode||document.body,{dragging:function(b){var d=a.get("map");if(!g){c==-1&&(f.style.display="none");d.set("autoPan_",d.get("autoPan"));var l=arguments.callee;g=j.addListener(d,"center_changed",function(){l.apply(this,[g.pixel])});a.set("editDragging_",true)}var k=b.getX?b:a.getMouseContainerPixel(b);g.pixel=k;k=d.fromContainerPixelToLatLng(k);d=a.get("path");if(e!=null){d.splice(e+1,0,k);f.index=e+1;e=null}else d[f.index]=k;a.notify("path")},dragend:function(){a.get("map").set("autoPan_",
false);g&&j.removeListener(g);a.set("editDragging_",false);g=null}});j.addDomListener(f,"mouseover",function(){a.toggleLabel(true)});j.addDomListener(f,"mouseout",function(){a.toggleLabel(false)});return f}function C(a,c,f,e){for(var g=0,b=0;b<f;b++)g+=a.getDistance(c[b],c[b+1]);g+=a.getDistance(c[f],e);return D(g)}function D(a){var c="";return c=a>=1E3?Math.round(a/100)/10+r.Units.km:Math.round(a*10)/10+r.Units.m}var w=__MapNSImpl__.Util,u=__MapNSImpl__.Config,x=t.MVCView,j=t.Event,v=t.Point,G=t.CanvasPolyline,
H=t.Polyline,A=t.Label,r=__MapNSImpl__.RC,E={"font-size":"12px","-moz-box-shadow":"2px 2px 8px #999999","-webkit-box-shadow":"2px 2px 8px #999999","box-shadow":"2px 2px 8px #999999","line-height":"15px","background-color":"#ffffff","font-weight":"bold",border:"1px solid #4b4b4b",padding:"2px 7px","-moz-border-radius":"3px","-webkit-border-radius":"3px","border-radius":"3px"};t=__MapNSImpl__.Class(x,{initialize:function(a){x.apply(this);this.set("model_",a);this.bindsTo(["path","strokeColor","strokeDashStyle",
"strokeOpacity","strokeWeight","fillColor","fillOpacity","zIndex","cursor","visible","panes_","map","editable","hasLabel","drawable","drawcursor","drawStartHint_","drawingHint_","destroy_","generalize","dpVertexes_","draw_","construct_","editIconUrl_"],a)},construct__changed:function(){var a=this.get("panes_");if(a){var c=new G;c.bindsTo(["strokeColor","strokeDashStyle","strokeOpacity","strokeWeight","fillColor","fillOpacity","cursor","zIndex","visible"],this);a.canvas.draw(c);this.set("canvasPolyline_",
c);this.registMouseEvents(this.get("fillColor")?c.getShape():c,["mouseover","mouseout","mousemove","click","dblclick","mousedown","mouseup","contextmenu"]);var f=document.createElement("div");a.overlayImage.appendChild(f);this.set("editPane_",f);this.set("editDots_",[]);this.set("editLabels_",[]);this.notify("draw_");var e=this,g=B(this,-1);g.style.zIndex=11;g.style.display="none";w.setCssSprite(g,this.get("editIconUrl_")||u.domain+"imgs/poly.png",[24,0]);var b=this.get("path");a.overlayLayer.appendChild(g);
this.set("addDot_",g);j.addListener(c,"mousemove",function(d,l){if(e.get("editable")){g.style.display="";g.style.left=l[0]-6+"px";g.style.top=l[1]-6+"px";g._lineIndex=l[2];if(e.get("hasLabel")&&!e.get("editDragging_")){var k=e.get("mouseLabel_"),m=e.get("map");m=C(m,b,l[2],d.latLng);k.setOptions({position:d.latLng,visible:true,content:m+'<br/><span style="font-weight:normal">'+r.PolyEditLabel.dragNew+"</span>"});g.title=""}else g.title=r.PolyEditLabel.dragNew}});j.addListener(c,"mouseover",function(){e.toggleLabel(true)});
j.addListener(c,"mouseout",function(){if(e.get("editable")){g.style.display="none";var d=e.get("mouseLabel_");d&&d.setVisible(false);e.toggleLabel(false)}})}},hasLabel_changed:function(){this.get("hasLabel")&&this.get("fillColor")&&this.set("hasLabel",false)},toggleLabel:function(a){if(!this.get("hasLabel")&&this.get("editable")){var c=this,f=this.get("labelListener_");f&&clearTimeout(f);f=setTimeout(function(){var e=c.get("path"),g=c.get("editLabels_"),b,d;for(b=0;(d=g[b])&&b<e.length;b++)d.get("visible")!=
a&&d.set("visible",a);c.set("labelListener_",null)},500);this.set("labelListener_",f)}},destroy__changed:function(){var a=this.get("panes_"),c=this.get("canvasPolyline_");if(a&&c){a.canvas.erase(c);c.unbinds(["strokeColor","strokeDashStyle","strokeOpacity","strokeWeight","fillColor","fillOpacity","cursor"]);a.overlayImage.removeChild(this.get("editPane_"));a.overlayLayer.removeChild(this.get("addDot_"));for(a=this.get("editLabels_");a.length!=0;)a.pop().setMap(null);this.set("canvasPolyline_",null);
(a=this.get("mask_"))&&j.trigger(a,"dblclick")}},path_changed:function(){this.notify("draw_")},douglasPeucker:function(){for(var a=[],c=function(d,l){for(var k=-1,m=d,p=[],s=d+1;s<l-1;s++){var h,i=a[s],n=a[d],q=a[l-1];h=null;h=n.getX();n=n.getY();var o=q.getX();q=q.getY();var y=i.getX();i=i.getY();if(h===o&&n===q){h=y-o;i=i-q;h=Math.sqrt(h*h+i*i)}else if(h===o)h=y-o;else if(n===q)h=i-q;else{var z=(h-o)/(q-n);h=(y+z*i+(q*h-n*o)/(n-q))/Math.sqrt(1+z*z)}h=Math.abs(h);if(k<h){k=h;m=s}}if(k>2){p=p.concat(c(d,
m+1));k=a[m];p.push(k.getX());p.push(k.getY());p=p.concat(c(m,l))}return p},f=this.get("path"),e=this.get("map"),g=0,b;b=f[g];g++){b=e.fromLatLngToPixel(b);a.push(b)}f=[];if(a.length!=0){f=c(0,a.length);f.unshift(a[0].getY());f.unshift(a[0].getX());f.push(a[a.length-1].getX());f.push(a[a.length-1].getY())}return f},editable_changed:function(){var a=this.get("editPane_"),c=this.get("panes_");if(this.get("editable")&&c){a&&(a.style.display="");a=this.get("mask_");if(a==null){a=document.createElement("div");
c=this.get("drawCursor")||"crosshair";a.style.cssText=["width:100%;height:100%;opacity:0.001;filter:alpha(opacity=0.1);z-index:0;position:absolute;top:0;left:0;background:black;cursor:",c+";"].join("");this.set("mask_",a)}}else a&&(a.style.display="none")},startDraw:function(){var a=this.get("panes_"),c=this.get("path"),f=this.get("map"),e=this;if(this.get("editable")&&c.length==0){var g=this.get("mapclick_");this.get("mapdblclick_");if(!g){var b=this.get("model_"),d=this.get("mask_");a=a.overlayImage.parentNode;
a.nextSibling?a.parentNode.insertBefore(d,a.nextSibling):a.parentNode.appendChild(d);var l=new H({strokeColor:this.get("strokeColor"),strokeWeight:this.get("strokeWeight"),strokeDashStyle:"dash",map:f});a=document.body.parentNode||document.body;j.addDomListener(a,"contextmenu",function(h){j.trigger(d,"dblclick",[h]);j.stopEvent(h)});this.set("mapclick",j.addDomListener(a,"click",function(h){h=e.getMouseLatLng(h);for(var i=0;i<c.length;i++)if(c[i].getLat()==h.getLat()&&c[i].getLng()==h.getLng())return;
c.push(h);e.notify("path");l.get("path")[0]=h;l.notify("path")}));var k=new v(-10,22),m=new v(-10,38),p=null,s=j.addDomListener(a,"mousemove",function(h){if(!p){f.set("autoPan_",true);var i=arguments.callee;p=j.addListener(f,"center_changed",function(){i.apply(this,[p.pixel])})}var n=h.getX?h:e.getMouseContainerPixel(h);p.pixel=n;n=f.fromContainerPixelToLatLng(n);var q=e.get("mouseLabel_"),o="";if(e.get("hasLabel")){o=null;if(c.length>0)o=C(f,c,c.length-1,n);o=c.length==0?e.get("drawStartHint_")||
r.PolyEditLabel.drawStart:e.get("drawingHint_")||r.PolyEditLabel.drawCurrent+o+'<br/><span style="font-weight:normal">'+r.PolyEditLabel.drawing;q.setOptions({visible:true,content:o,position:n,offset:c.length==0||e.get("drawingHint_")?k:m})}else{o=c.length==0?e.get("drawStartHint_")||r.PolyEditLabel.drawStart:e.get("drawingHint_")||r.PolyEditLabel.drawing;q.setOptions({visible:true,content:o,position:n,offset:k})}l.get("path")[1]=n;l.notify("path")});this.set("mapdblclick",j.addDomListener(d,"dblclick",
function(){if(c.length<2&&!e.get("fillColor")||c.length<3&&e.get("fillColor")||!b.get("map")){if(b.get("map")){b.set("map",null);j.trigger(b,"drawcancel")}}else j.trigger(b,"drawend");j.removeListener(e.get("mapclick"));j.removeListener(e.get("mapdblclick"));j.removeListener(p);j.removeListener(s);e.set("mapclick",null);f.set("autoPan_",false);d.parentNode&&d.parentNode.removeChild(d);l.setMap(null);e.get("mouseLabel_")&&e.get("mouseLabel_").setOptions({visible:false,offset:m})}))}}},draw__changed:function(){var a=
this.get("panes_"),c=this.get("canvasPolyline_");if(a&&c){a=[];var f=this.get("path"),e=this.get("map"),g=this.get("editable");this.startDraw();var b,d;for(b=0;d=f[b];b++){d=e.fromLatLngToPixel(d);a.push(d.getX(),d.getY())}if(g){d=this.get("editDots_");var l=this.get("editLabels_"),k=this.get("hasLabel");this.get("mouseLabel_")||this.set("mouseLabel_",new A({style:E,map:e,zIndex:1E5,offset:new v(-5,38),visible:false}));var m=a,p=this.get("editPane_");p.innerHTML="";var s=0;g=Math.max(m.length,d.length*
2);for(b=0;b<g;b+=2){var h=d[b/2],i=l[b/2];if(b>=m.length){h.style.display="none";i.setVisible(false)}else{if(!i){i=F(this,b/2,g/2);l.push(i)}var n=i.getContent().firstChild;if(k){i.setVisible(true);if(b!=0)s+=e.getDistance(f[b/2-1],f[b/2]);var q=D(s);i.setStyle(E);n.style.diplay="";n.parentNode.style.lineHeight="";n.parentNode.style.height=""}else{n.style.display="none";n.parentNode.style.lineHeight="0px";n.parentNode.style.height="14px";var o=i.getStyle();for(key in o)if(o.hasOwnProperty(key)){i.setStyle({});
break}}i.setPosition(f[b/2]);o=n.nextSibling;o.style.display=m.length<=4?"none":"";o.nextSibling.style.display=b!=m.length-2?"none":"";n.innerHTML=b==0?r.PolyEditLabel.start:b==m.length-2?r.PolyEditLabel.end+q:q;if(!h){h=B(this,b,g);d.push(h)}h.style.display="";p.appendChild(h);h.index=b/2;i.set("pathIndex_",b/2);i.setZIndex(b/2+10);h.style.left=m[b]-6+"px";h.style.top=m[b+1]-6+"px";i=[24,0];b===0&&(i=[0,0]);b===m.length-2&&(i=[12,0]);w.setCssSprite(h,this.get("editIconUrl_")||u.domain+"imgs/poly.png",
i)}}}else if(this.get("generalize")){a=this.douglasPeucker();this.set("dpVertexes_",a)}c.set("points",a.join(","))}}});x.setView("Polygon",t)})(__MapNS__);
