/*SOSO Map API beta 1.0.120202.7 @Tencent Research*/
(function(q){function y(d,c,b,f,g,i){i=i||0;var a=f[0],e=f[1]+i,k=b[0]-i,h=b[1]+i;f=f[1]-f[0];b=(b[2]*f-i*(b[0]+b[1])/2)/(f-i);i=a;f=e>a?10:-10;var j=a+f,m=(k-b)/(a-e),l=(h-b)/(a-e),n=k,o=h;h=["left","top","width","height"];if(g)h=["top","left","height","width"];for(var s=Math.ceil(Math.abs((e-i)/f)),z=0;z<s;z++){if(z===s-1)j=e;var A=b-(e-j)*m,B=b-(e-j)*l,t=Math.min(Math.min(Math.min(A,B),n),o);n=Math.max(Math.max(Math.max(A,B),n),o);o=Math.min(a,j);t=Math.floor(t);n=Math.ceil(n);o=Math.floor(o);
var C=document.createElement("div");C.style.cssText=["position:absolute;",h[0],":",t-k,"px;",h[1],":",o-i,"px;",h[2],":",n-t,"px;",h[3],":",Math.abs(j-a),"px;"].join("");r(C,c,g?[o,t]:[t,o]);n=A;o=B;a=j;j+=f;d.appendChild(C)}}var u=__MapNSImpl__.Util,w=q.Event,F=q.Marker,G=q.Label,H=q.Size,I=q.Point,v=q.MVCObject.checkers,J=q.Animation,E=v.checkInterface(__MapNSImpl__.Interfaces.LatLng),r=u.setCssSprite,p=u.setDomCoord,D=q.MVCView,x=u.getChildNodesByTag,K=__MapNSImpl__.Class(D,{initialize:function(d){D.apply(this);
this.set("model_",d);this.bindsTo(["destroy_","style","target","position","content","animation","visible","zIndex","autoMove","map","panes_","constructed_","draw_","sideBorder_"],d)},constructed__changed:function(){if(this.get("constructed_")){this.createInfoWindow();this.createShadow();this.notify("content")}},content_changed:function(){if(this.get("content")!==null){var d=this.getContentAndSize(true);if(d){this.set("natureSize_",d.size);this.drawContent(d.content,d.size)}}},getContentAndSize:function(d){var c=
this.get("infoWinDom_");if(!c)return null;var b=this.get("content");if(typeof b==="string"){var f=document.createElement("div");f.innerHTML=b;b=f}else try{b.parentNode&&b.parentNode.removeChild(b)}catch(g){}f=this.get("natureSize_");if(d||!f){d=this.get("style").width_range[1];f=b;c=c;var i=c.style.display;c.style.display="";f=f.cloneNode(true);c=c||document.body;var a=document.createElement("table");a.style.cssText="margin:0;padding:0;";a.cellSpacing=0;a.cellPadding=0;var e=a.insertRow(-1);e.style.cssText=
"margin:0;padding:0;";e=e.insertCell(-1);var k=u.getStyle(c,"font-size",true),h=u.getStyle(c,"line-height",true);e.style.cssText=["font-size:",k||"",";margin:0;padding:0;line-height:",h||"",";"].join("");e.appendChild(f);c.appendChild(a);a.offsetWidth>d&&(e.style.width=d+"px");d=[a.offsetWidth,a.offsetHeight];u.removeNode(a);c.style.display=i;f=d}return{content:b,size:f}},drawContent:function(d,c,b){this.drawInfoWindow(d,c,b);this.drawShadow();this.renderInfoWindow(typeof b!=="number")},drawInfoWindow:function(d,
c,b){var f=this.get("infoWinDom_");f=x(f,"div");var g=this.get("style"),i=g.top_left,a=g.bottom_right,e=g.margin,k=e[0]*2+c[0];c=e[1]*2+c[1];k<g.width_range[0]&&(k=g.width_range[0]);c<g.height_range[0]&&(c=g.height_range[0]);k+=b||0;c+=b||0;var h=[i[2],k-i[2]-a[2],a[2]],j=[i[3],c-i[3]-a[3],a[3]];i=[0,h[0],k-a[2]];var m=[0,j[0],c-a[3]];b=this.get("stemDirection_");for(var l=0;l<9;l++){a=l%3;var n=Math.floor(l/3);p(f[l],[i[a],m[n],h[a],j[n]])}this.set("contentDom_",f[11]);h=[h,j];i=[i,m];a=b===7||b===
1?0:1;j=b===1||b===3?-1:1;m=this.get("stemWidth_");var o=g.stem.align||"center",s=g.stem.offset||0;l=Math.floor((h[a][1]-m)/2);n=l+((h[a][1]-m)%2===0?0:1);l=o===q.ALIGN.LEFT?s:o===q.ALIGN.RIGHT?h[a][1]-m-s:Math.floor((h[a][1]-m)/2)+s;n=h[a][1]-m-l;o=[];o[a]=i[a][1];o[1-a]=i[1-a][1+j];o[2+a]=l;o[3-a]=h[1-a][1+j];p(f[b],o);b=[];b[a]=i[a][1]+l;b[1-a]=i[1-a][1+j];b[2+a]=m;b[3-a]=h[1-a][1+j];p(f[9],b);b=[];b[a]=i[a][1]+l+m;b[1-a]=i[1-a][1+j];b[2+a]=n;b[3-a]=h[1-a][1+j];p(f[10],b);b=[];b[a]=i[a][1]+l;b[1-
a]=i[1-a][1+j]+(j+1)/2*h[1-a][1+j];p(f[12],b);p(f[11],[e[0],e[1],k-2*e[0],c-2*e[1]]);if(d!==null){for(;f[11].firstChild;)f[11].removeChild(f[11].firstChild);f[11].appendChild(d);w.trigger(this.get("model_"),"domready")}d=this.get("stemOffset_");e=[];e[a]=b[a]+d[a];e[1-a]=b[1-a]+d[1-a];this.set("pixelOffset_",e);this.set("pixelSize_",[k,c]);if(g=g.close){a=e=0;e=g.align;d=e%3;b=Math.floor(e/3);h=g.margin;e=(k-g.coordinate[2])/2*d;a=(c-g.coordinate[3])/2*b;d<2?e+=h[0]:e-=h[0];b<2?a+=h[1]:a-=h[1];p(f[13],
[e,a])}},drawShadow:function(){var d=this.get("shadowDom_");if(d){d=x(d,"div");var c=this.get("style"),b=c.shadow,f=b.stem,g=f.blur,i=b.top_left,a=b.bottom_right,e=this.get("pixelSize_"),k=a[0]+a[1]-i[1];a=Math.floor(e[1]/1.414)-Math.floor(c.bottom_right[3]/1.414);var h=a+g,j=c.bottom_right[2],m=Math.floor(c.bottom_right[3]/1.414);c=c.top_left[2];r(d[0],b.url,[i[0]-h,i[1]-g]);p(d[0],[-h,-g,e[0],h]);r(d[1],b.url,[k-h,i[1]-g]);p(d[1],[e[0]-h,-g,h,h]);p(d[2],[Math.ceil(-e[1]/1.414)-g,a]);p(d[6],[e[0]-
a-j-m,a]);b=f.x[1]-f.x[0]+2*g;f=e[0]-c-m-j;e=Math.floor((f-b)/2);f=e+((f-b)%2===0?0:1);c=c-a;m+=g;p(d[3],[c,a,e,m]);p(d[4],[c+e,a,b,m]);p(d[5],[c+e+b,a,f,m]);p(d[7],[c+e,a+m])}},pop:function(){var d=this.get("popAnimation_"),c=this.getContentAndSize();if(c){this.get("contentDom_").style.overflow="hidden";var b=this.get("style");if(!d){var f=this;d=new q.Fx({fps:40,callback:function(g){f.drawContent(null,g,0)},method:q.Fx.easeInOutBack,duration:0.3});this.set("popAnimation_",d);w.addListener(d,"end",
function(){f.get("contentDom_").style.overflow="";f.renderInfoWindow(true)})}d.getStatus()===1&&d.stop();d.set("begins",[b.width_range[0],b.height_range[0]]);d.set("ends",c.size);d.start()}},visible_changed:function(){var d=this.get("visible");d&&this.get("animation")===0||this.get("animation")===J.POP?this.pop():this.renderInfoWindow(d)},changed:function(d){if(d==="position"||d==="altitude_")this.renderInfoWindow()},target_changed:function(){this.set("position",this.get("target"))},position_changed:function(){var d=
this.get("position")||this.get("target");this.unbind("altitude_",d);d&&!E(d)&&d.getPosition&&this.bindTo("altitude_",d);this.renderInfoWindow(true)},renderInfoWindow:function(d){var c=this.get("infoWinDom_"),b=this.get("position")||this.get("target"),f=this.get("map"),g=this.get("pixelOffset_"),i=this.get("stemDirection_");if(c&&b&&f&&g){c.style.display=this.get("visible")?"":"none";c.style.zIndex=this.get("zIndex")||0;var a=null,e=null,k=0,h=0,j,m=this.get("altitude_")||0,l=0;if(E(b)){var n=f.fromLatLngToPixel(b);
a=n.getX()-g[0];e=n.getY()-g[1]}else{var o=b.getPosition();n=f.fromLatLngToPixel(o);if(v.isInstanceOf(F)(b)){l=b.getIcon();if(o&&l){e=l.get("anchor_");j=l.get("size_");a=n.getX()-g[0]-e.getX();e=n.getY()-g[1]-e.getY()}}if(v.isInstanceOf(G)(b)){j=b.get("size");e=b.get("anchor");a=b.get("offset");l=b=0;if(a){v.isInstanceOf(H)(a)&&(b=a.getWidth(),l=a.getHeight());v.isInstanceOf(I)(a)&&(b=a.getX(),l=a.getY())}a=n.getX()-g[0]-e.getX()+b;e=n.getY()-g[1]-e.getY()+l}switch(i){case 1:e+=j.getHeight();a+=j.getWidth()/
2;k=-j.getHeight();break;case 7:a+=j.getWidth()/2;k=j.getHeight();break;case 3:a+=j.getWidth();h=-j.getWidth();break;case 5:e+=j.getHeight()/2;h=j.getWidth()}e-=m;l=j.getHeight()}if(a!==null&&e!==null){g=this.get("style");c.style.left=a+g.offset[0]+"px";c.style.top=e+g.offset[1]+"px";i=this.get("shadowDom_");c=this.get("pixelSize_");g=this.get("pixelOffset_");if(i){n=this.get("style").shadow.stem;i.style.display=this.get("visible")?"":"none";j=Math.floor(g[1]/1.414);n=n.offset;m=m||0;l=m+l;i.style.left=
a+j+n[0]+l+"px";i.style.top=e+(g[1]-j)+n[1]+l-Math.floor(l/1.414)+"px"}if(m)e+=this.get("altitude_");if(this.get("autoMove")&&d&&this.get("visible")){l=this.get("model_").get("originPosition_");d=Math.min(g[0],0)+a-l[0];m=Math.min(g[1],1)+e-l[1];a=Math.max(g[0],c[0])+a-l[0];e=Math.max(g[1],c[1])+e-l[1];h<0&&(d+=h);h>0&&(a+=h);k<0&&(m+=k);k>0&&(e+=k);k=f.getViewSize();h=[0,0];c=this.get("sideBorder_")||[0,0,0,0];d<c[3]&&(h[0]=-d+10+c[3]);m<c[0]&&(h[1]=-m+10+c[0]);a>k.getWidth()-c[1]&&(h[0]=k.getWidth()-
a-10-c[1]);e>k.getHeight()-c[2]&&(h[1]=k.getHeight()-e-10-c[2]);f.moveBy(new q.Size(h[0],h[1]))}}}},draw__changed:function(){this.renderInfoWindow()},destroy__changed:function(){var d=this.get("panes_");if(d){if(this.get("infoWinDom_")){d.floatPane.removeChild(this.get("infoWinDom_"));this.set("infoWinDom_",null)}if(this.get("shadowDom_")){d.floatShadow.removeChild(this.get("shadowDom_"));this.set("shadowDom_",null)}w.trigger(this.get("model_"),"remove")}},createInfoWindow:function(){var d=this.get("panes_");
if(d){var c=!this.get("infoWinDom_"),b=this.getDom("infoWinDom_",d.floatPane);d=b.style;d.fontSize="14px";d.lineHeight="20px";d.display="none";d=this.get("style");var f=d.url,g=d.top_left,i=d.bottom_right;if(c){var a=[];for(c=0;c<14;c++)a.push('<div style="position:absolute;"></div>');b.innerHTML=a.join("")}b=x(b,"div");a=[g[0],g[0]+g[2],i[0]];var e=[g[1],g[1]+g[3],i[1]];for(c=0;c<9;c++)r(b[c],f,[a[c%3],e[Math.floor(c/3)]]);c=d.stem;a=0;e=[];var k=[],h=0,j=null,m=null;if(c.x.length){j=[c.y];if(c.y>
i[1]){a=7;e=[c.x[0],i[1]];k=[c.x[1],i[1]];j.unshift(i[1]+i[3])}else{e=[c.x[0],g[1]];k=[c.x[1],g[1]];a=1;j.unshift(g[1])}y(b[12],f,c.x,j);h=c.x[0]-c.x[1];m=[c.x[2]-c.x[0],j[1]-j[0]]}if(c.y.length){j=[c.x];if(c.x<g[0]){e=[g[0],c.y[0]];k=[g[0],c.y[1]];a=3;j.unshift(g[0])}else{e=[i[0],c.y[0]];k=[i[0],c.y[1]];a=5;j.unshift(i[0]+i[2])}y(b[12],f,c.y,j,true);h=c.y[0]-c.y[1];m=[j[1]-j[0],c.y[2]-c.y[0]]}r(b[9],f,e);r(b[10],f,k);r(b[a],f,k);this.set("stemDirection_",a);this.set("stemHeight_",Math.abs(j[1]-j[0]));
this.set("stemWidth_",Math.abs(h));this.set("stemOffset_",m);if(d=d.close){f=d.coordinate;r(b[13],d.url,f);p(b[13],[null,null,f[2],f[3]]);b[13].style.cursor="pointer";var l=this;w.addDomListener(b[13],"click",function(){l.set("visible",false)})}}},getDom:function(d,c){var b=this.get(d);if(!b){b=document.createElement("div");b.style.cssText="position:absolute;";this.set(d,b)}b.parentNode!==c&&c.appendChild(b);return b},createShadow:function(){var d=this.get("style").shadow;if(!(this.get("stemDirection_")!==
7||!d)){var c=this.get("panes_"),b=!this.get("shadowDom_"),f=this.getDom("shadowDom_",c.floatShadow);f.style.display="none";var g=this.get("style");c=d.url;var i=d.top_left,a=d.bottom_right;d=d.stem;var e=d.blur||0;if(b){b=[];for(var k=0;k<8;k++)b.push('<div style="position:absolute;"></div>');f.innerHTML=b.join("")}f=x(f,"div");b=Math.floor(g.bottom_right[3]/1.414);k=g.bottom_right[2];g=g.top_left[2];var h=a[1]-b;i=-a[1]+i[0]+i[1];b=Math.ceil(b)+e;r(f[2],c,[i-e,h]);p(f[2],[null,null,g+b,b]);r(f[4],
c,[d.x[0]-e,h]);p(f[4],[null,null,d.x[1]-d.x[0]+2*e,b]);r(f[3],c,[d.x[1]+e,h]);r(f[5],c,[d.x[1]+e,h]);r(f[6],c,[a[0]-k,h]);p(f[6],[null,null,k+b,b]);y(f[7],c,d.x,[h+b,d.y],false,e)}}});D.setView("InfoWindow",K)})(__MapNS__);
